### ISSUE TITLE
Cannot read file

### ISSUE THREAD

**Issue by Monal5031** [Monal5031/TextToSpeech-Converter#2]
It is not able to read the file. 
Instead it just tends to create a new one even though it exists.
Further it read's the file's path as the text inside it.

**Comment by Prakash2403** [comment]
You can't directly use file path in Scanner constructor. You have to pass a File object to Scanner constructor. Syntax would look like:

Scanner in = new Scanner(new File(path));
path must be absolute path to that file.

It will work fine after this. 

Tip: Try to maintain a consistent indentation throughout the project. It will be easy for you and others to debug the project. Also, use java naming conventions and use some meaningful names.

**Comment by Monal5031** [comment]
Okay Thanks!
Also, about the indentations i'm using netbeans for this and it indents the code itseld that's why this problem has occurred with indentation, thanks for pointing it out i'll clean it up :) 
and also will change the names too thanks :)

**Comment by Monal5031** [comment]
Thank you it just worked perfectly updated my code and it is working just fine.
